#import.sql file
INSERT INTO AUTHORS (NAME,RATING)VALUES("Super Band",1);
INSERT INTO AUTHORS (NAME,RATING)VALUES("Small Band",1);
INSERT INTO ALBUMS (NAME,AUTHOR_ID,RATING)VALUES("Super Album #1",1,1);
INSERT INTO SONGS (NAME,ALBUM_ID,RATING)VALUES("Super Song #123",1,1);

insert into USERS(ID, PASSWORD, USERNAME) values(1, '$2a$10$bnC26zz//2cavYoSCrlHdecWF8tkGfPodlHcYwlACBBwJvcEf0p2G', 'svlada@gmail.com');
insert into ROLES(ROLE_ID, NAME) values(1, 'ADMIN');
