#import.sql file
INSERT INTO AUTH_USERS (USER_NAME,PASSWORD,EMAIL)VALUES("Nail","1234","xd.gmail.com");
INSERT INTO AUTH_USERS (USER_NAME,PASSWORD,EMAIL)VALUES("Nazar","4321","nazar.gmail.com");
INSERT INTO AUTHOURS (NAME)VALUES("Super Band");
INSERT INTO AUTHOURS (NAME)VALUES("Small Band");
INSERT INTO ALBUMS (NAME,AUTHOUR_ID)VALUES("Super Album #1",1);
INSERT INTO SONGS (NAME,ALBUM_ID)VALUES("Super Song #123",1);
INSERT INTO SONGS (NAME,ALBUM_ID)VALUES("Super Song #563",1);
INSERT INTO SONGS (NAME,ALBUM_ID)VALUES("Super Song #85",1);
